//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPermission
    {
        public int ID { get; set; }
        public int Store_ID { get; set; }
        public int Supplier_ID { get; set; }
        public int Product_ID { get; set; }
        public int Product_Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Manufacture_Date { get; set; }
        public int Expiration_Duration { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
